name: CI Checks

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x.y
        uses: actions/setup-go@v5
        with:
          go-version: ^1.23.1

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Copy File
        run: |
          mkdir artifacts
          cp api artifacts/.

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: artifacts
